server:
  port: 8881

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: false